version: '3.1'
services:
  casdoor:
    restart: always
    build:
      context: ../
      dockerfile: casdoor/Dockerfile
      target: STANDARD
    entrypoint: /bin/sh -c './server --createDatabase=true'
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      RUNNING_IN_DOCKER: "true"
      CASDOOR_DB_PASS: "${CASDOOR_DB_PASS:-casdoor2024}"
    volumes:
      - ./conf:/conf/
      - ./init_data.json:/init_data.json
    networks:
      - casdoor-network

  postgres:
    restart: always
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: casdoor
      POSTGRES_USER: casdoor
      POSTGRES_PASSWORD: "${CASDOOR_DB_PASS:-casdoor2024}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - casdoor-network

volumes:
  postgres-data:

networks:
  casdoor-network:
    driver: bridge
